### ISSUE TITLE
[J-M] CEQR: Schools data and regressions

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-work-planning#18]
This epic consists of data tables to update and related regressions. Tables are listed in this checklist, and separate regression issues are connected below.

**Tables to update:**
- [x] sca_e_projections_by_boro
  - [x] 2019
- [x] sca_e_projections_by_sd
  - [x] 2017
  - [x] 2018
  - [x] 2019
- [x] sca_capacity_projects
  - [x] 2019/11 (may have been missed)
  - [x] 2020/02 (new)
- [x] ceqr_school_buildings
  - [x] 2019
- [x] ceqr_school_buildings
  - [x] 2019
~- [ ] doe_significant_utilization_changes~ delayed
  ~- [ ] 2020 (new, pending capital planning)~ delayed

**Comment by allthesignals** [comment]
Going through this, I'm seeing this table in the staging database:

> sca_capacity_projects
>  **2019/11 (may have been missed)**

But I think I need to update the Data Package to point to it. Doing that now.

**Comment by allthesignals** [comment]
Waiting to find out where the new doe_significant_utilization data is (2020). Not sure if it's in capital planning/edm's court.

**Comment by allthesignals** [comment]
Related to SCA Capacity Projects, finding that all of these columns changed (were dropped):

planned_end_date
total_est_cost
funding_current_budget
funding_previous
pct_funded

Going to see how extensively they're used in the data, if at all.

**Comment by allthesignals** [comment]
Spot check shows that these sca datasets seem to work!
