### ISSUE TITLE
[K] CPP: Update FacDB, DevDB, CPDB, CBBR data

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-work-planning#21]
- [ ] CPDB: Available on Carto and ready to be updated in the Capital Planning Platform.  The latest 7 data tables that make up the Capital Projects Database have been uploaded to Carto, they end in "_20apr"

- [ ] DevDB: is up on Carto as devdb_housing_pts_20v1 and is ready to go into the Capital Planning Platform staging environment. The schema is the same, but please let us know if you have any issues swapping out the data.

- [ ] CBBR: Schema changes. Issue: https://github.com/NYCPlanning/labs-cp-platform/issues/12

- [ ] FacDB: Not ready yet, don't need to update in sprint K
